package hand.hmw.framework.quartz.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 12 16:04:53 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SchedulejobsBySqlVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SchedulejobsBySqlVOImpl() {
    }
}
